### ISSUE TITLE
Not all data is available

### ISSUE THREAD

**Issue by ravsit-activum** [mbugert/connectbox-prometheus#1]
Hi,

I get only these data:

connectbox_device_info{cable_modem_status="Operational",cm_provision_mode="IPv4",docsis_mode="DOCSIS 3.0",firmware_version="CH7465LG-NCIP-6.12.18.25-2p6-NOSH",gw_provision_mode="IPv4",hardware_version="5.01",operator_id="LIBERTYGLOBAL"} 1.0
connectbox_provisioning_status{connectbox_provisioning_status="Online"} 1.0
connectbox_provisioning_status{connectbox_provisioning_status="Partial Service (DS only)"} 0.0
connectbox_provisioning_status{connectbox_provisioning_status="Partial Service (US only)"} 0.0
connectbox_provisioning_status{connectbox_provisioning_status="Partial Service (US+DS)"} 0.0
connectbox_uptime_seconds_total 118093.0
connectbox_tuner_temperature_celsius 26.666666666666668
connectbox_temperature_celsius 16.666666666666668
connectbox_scrape_success 0.0

At log i get:
2020-04-15 22:19:59,466 - connectbox_exporter - DEBUG - Logging in at 192.168.0.1
DEBUG:connectbox_exporter:Logging in at 192.168.0.1
INFO:compal:302 [http://192.168.0.1/] => '../common_page/login.html' [token: 1203887360]
INFO:compal:[login] SID 2710463232
2020-04-15 22:20:00,901 - connectbox_exporter - DEBUG - Querying fun=1...
DEBUG:connectbox_exporter:Querying fun=1...
2020-04-15 22:20:01,591 - connectbox_exporter - DEBUG - Querying fun=2...
DEBUG:connectbox_exporter:Querying fun=2...
2020-04-15 22:20:02,050 - connectbox_exporter - DEBUG - Querying fun=144...
DEBUG:connectbox_exporter:Querying fun=144...
2020-04-15 22:20:02,561 - connectbox_exporter - DEBUG - Querying fun=136...
DEBUG:connectbox_exporter:Querying fun=136...
2020-04-15 22:20:03,045 - connectbox_exporter - DEBUG - Querying fun=123...
DEBUG:connectbox_exporter:Querying fun=123...
2020-04-15 22:20:04,624 - connectbox_exporter - ERROR - 'NoneType' object has no attribute 'text'
ERROR:connectbox_exporter:'NoneType' object has no attribute 'text'
2020-04-15 22:20:04,625 - connectbox_exporter - DEBUG - Logging out.
DEBUG:connectbox_exporter:Logging out.

I live in Poland and I use  Compal CH7465LG cable modem from UPC.

**Comment by mbugert** [comment]
Hi @ravsit-activum
thanks for getting in touch.

I just released v0.2.1 on pypi which offers more verbose log outputs. Could you please run this updated version via `connectbox_exporter -vv config.yml` and then post the raw XML output for `fun=123` here? There will probably be some MAC addresses and hostnames of your devices in the XML. I would recommend you to anonymize those before posting. :+1:

**Comment by ravsit-activum** [comment]
I see plain XMLs at logs.
After some readings I have noticed that in my configuratuin i havn't got IPV6 so it failes in xml2metric.py at this line:
            ipv6_address = client.find("IPv6Addr").text

after this change:
            ipv6_address = "IPv6" # client.find("IPv6Addr").text
it goes without error.

Now i get more data from fun=144.

So, thanks for this more verbose log outputs.


At this point I need one more Metric:
connectbox_wifi_user_speed_mbit | WIFI user network speed

These data are in LanUserTable tree at WIFI list in clientinfo structure:
`<LanUserTable>
<Ethernet>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>
<interface>Ethernet 2</interface>
<IPv4Addr>192.168.0.x/24</IPv4Addr>
<index>20</index>
<interfaceid>2</interfaceid>
<hostname>Unknown</hostname>
<MACAddr>4C:CC:6A:x:x:x</MACAddr>
<method>2</method>
<leaseTime>00:00:00:00</leaseTime>
<speed>1000</speed>
</clientinfo>
</Ethernet>
<WIFI>
<clientinfo>
<interface>Cxxxxxxxx</interface>
<IPv4Addr>192.168.0.x/24</IPv4Addr>
<index>0</index>
<interfaceid>3</interfaceid>
<hostname>Unknown</hostname>
<MACAddr>74:E5:0B:x:x:x</MACAddr>
<method>2</method>
<leaseTime>00:00:00:00</leaseTime>
<speed>72</speed>
</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
<clientinfo>...</clientinfo>
</WIFI>
<totalClient>22</totalClient>
<Customer>upc</Customer>
</LanUserTable>
`

By the way:
count(connectbox_lan_user_speed_mbit{instance="localhost:9705"}) doesn't count WIFI users.
but `<totalClient>22</totalClient>` have all users LAN and WIFI

Regards

**Comment by mbugert** [comment]
Thank you. I rebooted my modem earlier and now I'm seeing the same issue. Expect a fix this evening.

**Comment by mbugert** [comment]
Hi @ravsit-activum please try again with the newest version from pypi. The Grafana dashboard is updated, too (don't know if you have been using it).

**Comment by mbugert** [comment]
I consider this resolved.
